; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif8266
board = d1_mini_pro
framework = arduino
build_src_filter = +<*.h> +<main-${PIOENV}.cpp>
build_type = debug
monitor_filters = esp8266_exception_decoder, default
lib_deps = 
	fastled/FastLED@^3.6.0
	regenbogencode/ESPNowW@^1.0.2
	thomasfredericks/Bounce2@^2.72
	adafruit/Adafruit SSD1306@^2.5.10

[env:master]
[env:slave]
